// ─── 100 Language Config ─────────────────────────────────────────────────────
// Each entry: [code, name, text-direction]
// To add a new language: append one line here + add slugs to TOPIC_SLUGS below.
export const LANGUAGE_CONFIG = [
  ['en',    'English',              'ltr'],
  ['es',    'Spanish',              'ltr'],
  ['pt',    'Portuguese',           'ltr'],
  ['fr',    'French',               'ltr'],
  ['it',    'Italian',              'ltr'],
  ['de',    'German',               'ltr'],
  ['hi',    'Hindi',                'ltr'],
  ['ar',    'Arabic',               'rtl'],
  ['zh-cn', 'Chinese Simplified',   'ltr'],
  ['ja',    'Japanese',             'ltr'],
  ['ru',    'Russian',              'ltr'],
  ['id',    'Indonesian',           'ltr'],
  ['ko',    'Korean',               'ltr'],
  ['tr',    'Turkish',              'ltr'],
  ['bn',    'Bengali',              'ltr'],
  ['ur',    'Urdu',                 'rtl'],
  ['vi',    'Vietnamese',           'ltr'],
  ['th',    'Thai',                 'ltr'],
  ['fa',    'Persian',              'rtl'],
  ['ms',    'Malay',                'ltr'],
  ['fil',   'Filipino',             'ltr'],
  ['nl',    'Dutch',                'ltr'],
  ['pl',    'Polish',               'ltr'],
  ['ta',    'Tamil',                'ltr'],
  ['te',    'Telugu',               'ltr'],
  ['mr',    'Marathi',              'ltr'],
  ['gu',    'Gujarati',             'ltr'],
  ['kn',    'Kannada',              'ltr'],
  ['ml',    'Malayalam',            'ltr'],
  ['pa',    'Punjabi',              'ltr'],
  ['ne',    'Nepali',               'ltr'],
  ['uk',    'Ukrainian',            'ltr'],
  ['ro',    'Romanian',             'ltr'],
  ['el',    'Greek',                'ltr'],
  ['cs',    'Czech',                'ltr'],
  ['sv',    'Swedish',              'ltr'],
  ['he',    'Hebrew',               'rtl'],
  ['zh-tw', 'Chinese Traditional',  'ltr'],
  ['no',    'Norwegian',            'ltr'],
  ['da',    'Danish',               'ltr'],
  ['fi',    'Finnish',              'ltr'],
  ['hu',    'Hungarian',            'ltr'],
  ['sk',    'Slovak',               'ltr'],
  ['bg',    'Bulgarian',            'ltr'],
  ['hr',    'Croatian',             'ltr'],
  ['sr',    'Serbian',              'ltr'],
  ['sl',    'Slovenian',            'ltr'],
  ['lt',    'Lithuanian',           'ltr'],
  ['lv',    'Latvian',              'ltr'],
  ['et',    'Estonian',             'ltr'],
  ['ka',    'Georgian',             'ltr'],
  ['hy',    'Armenian',             'ltr'],
  ['az',    'Azerbaijani',          'ltr'],
  ['kk',    'Kazakh',               'ltr'],
  ['uz',    'Uzbek',                'ltr'],
  ['mn',    'Mongolian',            'ltr'],
  ['my',    'Burmese',              'ltr'],
  ['km',    'Khmer',                'ltr'],
  ['si',    'Sinhala',              'ltr'],
  ['am',    'Amharic',              'ltr'],
  ['sw',    'Swahili',              'ltr'],
  ['yo',    'Yoruba',               'ltr'],
  ['ig',    'Igbo',                 'ltr'],
  ['ha',    'Hausa',                'ltr'],
  ['zu',    'Zulu',                 'ltr'],
  ['af',    'Afrikaans',            'ltr'],
  ['sq',    'Albanian',             'ltr'],
  ['bs',    'Bosnian',              'ltr'],
  ['mk',    'Macedonian',           'ltr'],
  ['mt',    'Maltese',              'ltr'],
  ['cy',    'Welsh',                'ltr'],
  ['gl',    'Galician',             'ltr'],
  ['ca',    'Catalan',              'ltr'],
  ['eu',    'Basque',               'ltr'],
  ['is',    'Icelandic',            'ltr'],
  ['ga',    'Irish',                'ltr'],
  ['be',    'Belarusian',           'ltr'],
  ['ps',    'Pashto',               'rtl'],
  ['sd',    'Sindhi',               'rtl'],
  ['ku',    'Kurdish',              'ltr'],
  ['so',    'Somali',               'ltr'],
  ['mg',    'Malagasy',             'ltr'],
  ['ht',    'Haitian Creole',       'ltr'],
  ['ceb',   'Cebuano',              'ltr'],
  ['jv',    'Javanese',             'ltr'],
  ['su',    'Sundanese',            'ltr'],
  ['xh',    'Xhosa',                'ltr'],
  ['st',    'Sesotho',              'ltr'],
  ['fy',    'Frisian',              'ltr'],
  ['lb',    'Luxembourgish',        'ltr'],
  ['tk',    'Turkmen',              'ltr'],
  ['ky',    'Kyrgyz',               'ltr'],
  ['lo',    'Lao',                  'ltr'],
  ['ti',    'Tigrinya',             'ltr'],
  ['rw',    'Kinyarwanda',          'ltr'],
  ['or',    'Odia',                 'ltr'],
  ['as',    'Assamese',             'ltr'],
  ['ug',    'Uyghur',               'rtl'],
  ['sn',    'Shona',                'ltr'],
  ['ny',    'Chichewa',             'ltr'],
] as const

export type LangCode = typeof LANGUAGE_CONFIG[number][0]

// ─── 7 Topic Slug Maps ────────────────────────────────────────────────────────
// Only non-English (localized) slugs are listed. All others use `defaultSlug`.
export interface TopicDef {
  key: string
  priority: number
  defaultSlug: string
  slugs: Partial<Record<string, string>>
}

export const TOPIC_DEFS: TopicDef[] = [
  {
    key: 'numerology',
    priority: 0.9,
    defaultSlug: 'free-numerology-reading',
    slugs: {
      es: 'numerologia-gratis',
      pt: 'numerologia-gratis',
      fr: 'numerologie-gratuite',
      it: 'numerologia-gratis',
      de: 'numerologie-kostenlos',
      hi: 'numerology-hindi',
      'zh-cn': 'mianfei-shuxue',
      'zh-tw': 'mianfei-shuxue',
      ja: 'muryou-suuji-uranai',
      ru: 'numerologiya-besplatno',
      ko: 'muryo-surisunsul',
      ar: 'qiraah-alarqam-majania',
      fa: 'adadshenasi-rayegan',
      tr: 'ucretsiz-numeroloji',
      bn: 'binamulye-sankhyatattwa',
      id: 'numerologi-gratis',
    },
  },
  {
    key: 'nameNumerology',
    priority: 0.9,
    defaultSlug: 'numerology-by-name',
    slugs: {
      es: 'numerologia-nombre',
      pt: 'numerologia-nome',
      fr: 'numerologie-prenom',
      it: 'numerologia-nome',
      de: 'numerologie-name',
      hi: 'naam-se-bhavishya',
      'zh-cn': 'xingming-shuxue',
      'zh-tw': 'xingming-shuxue',
      ja: 'namae-suuji',
      ru: 'numerologiya-po-imeni',
      ko: 'ireum-surisunsul',
      ar: 'alarqam-bilaism',
      fa: 'adadshenasi-name',
      tr: 'isme-gore-numeroloji',
      bn: 'namer-sankhyatattwa',
      id: 'numerologi-nama',
    },
  },
  {
    key: 'number11',
    priority: 0.8,
    defaultSlug: 'meaning-of-number-11',
    slugs: {
      es: 'que-significa-numero-11',
      pt: 'o-que-significa-numero-11',
      fr: 'signification-nombre-11',
      it: 'significato-numero-11',
      de: 'bedeutung-zahl-11',
      hi: 'ank-11-ka-arth',
      'zh-cn': 'shuzi-11-yiyi',
      'zh-tw': 'shuzi-11-yiyi',
      ja: 'suuji-11-imi',
      ru: 'znachenie-chisla-11',
      ko: '숫자-11-uimi',
      ar: 'mana-raqam-11',
      fa: 'mani-adad-11',
      tr: '11-sayisinin-anlami',
      bn: 'sankhya-11-er-artha',
      id: 'arti-angka-11',
    },
  },
  {
    key: 'vedicAstrology',
    priority: 0.8,
    defaultSlug: 'free-vedic-astrology',
    slugs: {
      es: 'astrologia-vedica-gratis',
      pt: 'astrologia-vedica-gratis',
      fr: 'astrologie-vedique-gratuite',
      it: 'astrologia-vedica-gratis',
      de: 'vedische-astrologie-kostenlos',
      hi: 'vedic-jyotish-hindi',
      'zh-cn': 'mianfei-vedic-zhanxing',
      'zh-tw': 'mianfei-vedic-zhanxing',
      ja: 'muryou-vedic-占星術',
      ru: 'vedicheskaya-astrologiya-besplatno',
      ko: 'muryo-vedic-jeomsul',
      ar: 'altanjim-alvedic-almajani',
      fa: 'astrology-vedic-rayegan',
      tr: 'ucretsiz-vedik-astroloji',
      bn: 'binamulye-vedic-jyotish',
      id: 'astrologi-veda-gratis',
    },
  },
  {
    key: 'birthChart',
    priority: 0.9,
    defaultSlug: 'free-birth-chart',
    slugs: {
      es: 'carta-natal-gratis',
      pt: 'mapa-natal-gratis',
      fr: 'theme-astral-gratuit',
      it: 'tema-natale-gratis',
      de: 'geburtshoroskop-kostenlos',
      hi: 'janam-kundali-hindi',
      'zh-cn': 'mianfei-chusheng-tiantu',
      'zh-tw': 'mianfei-chusheng-tiantu',
      ja: 'muryou-shussei-horoscope',
      ru: 'besplatnaya-karta-rozhdeniya',
      ko: 'muryo-chulssaeng-chado',
      ar: 'khart-almilad-almajani',
      fa: 'naghsh-tavalod-rayegan',
      tr: 'ucretsiz-dogum-haritasi',
      bn: 'binamulye-janma-kundali',
      id: 'bagan-kelahiran-gratis',
    },
  },
  {
    key: 'compatibility',
    priority: 0.8,
    defaultSlug: 'numerology-compatibility',
    slugs: {
      es: 'compatibilidad-numerologica',
      pt: 'compatibilidade-numerologica',
      fr: 'compatibilite-numerologique',
      it: 'compatibilita-numerologica',
      de: 'numerologie-kompatibilitaet',
      hi: 'numerology-milan',
      'zh-cn': 'shuxue-xianghe-xing',
      'zh-tw': 'shuxue-xianghe-xing',
      ja: 'suuji-aishou',
      ru: 'sovmestimost-numerologiya',
      ko: 'surisunsul-gunghabseong',
      ar: 'altawafuq-alaqami',
      fa: 'sazegari-adadshenasi',
      tr: 'numeroloji-uyumlulugu',
      bn: 'sankhyatattwa-mil',
      id: 'kecocokan-numerologi',
    },
  },
  {
    key: 'astrologyChart',
    priority: 0.9,
    defaultSlug: 'free-astrology-chart',
    slugs: {
      es: 'mapa-astral-gratis',
      pt: 'mapa-astral-gratis',
      fr: 'carte-natale-gratuite',
      it: 'mappa-astrale-gratis',
      de: 'geburtstagskarte-kostenlos',
      hi: 'janam-patrika-hindi',
      'zh-cn': 'mianfei-zhanxing-tiantu',
      'zh-tw': 'mianfei-zhanxing-tiantu',
      ja: 'muryou-占星術-chato',
      ru: 'besplatnaya-astrologia-karta',
      ko: 'muryo-jeomsul-chado',
      ar: 'khart-altanjim-almajani',
      fa: 'naghsh-astrology-rayegan',
      tr: 'ucretsiz-astroloji-haritasi',
      bn: 'binamulye-jyotish-chart',
      id: 'bagan-astrologi-gratis',
    },
  },
]
