export type MotherTongueOption = {
  code: string
  native: string
  english: string
  flag: string
}

export const MOTHER_TONGUE_OPTIONS: MotherTongueOption[] = [
  { code: 'ar',    native: 'العربية',        english: 'Arabic',             flag: '🇸🇦' },
  { code: 'fa',    native: 'فارسی',           english: 'Persian (Farsi)',    flag: '🇮🇷' },
  { code: 'prs',   native: 'دری',             english: 'Dari',               flag: '🇦🇫' },
  { code: 'ps',    native: 'پښتو',            english: 'Pashto',             flag: '🇦🇫' },
  { code: 'ur',    native: 'اردو',            english: 'Urdu',               flag: '🇵🇰' },
  { code: 'ks',    native: 'کٲشُر',           english: 'Kashmiri',           flag: '🇮🇳' },
  { code: 'sd',    native: 'سنڌي',            english: 'Sindhi',             flag: '🇵🇰' },
  { code: 'ug',    native: 'ئۇيغۇرچە',        english: 'Uyghur',             flag: '🇨🇳' },
  { code: 'dv',    native: 'ދިވެހި',           english: 'Dhivehi',            flag: '🇲🇻' },
  { code: 'he',    native: 'עברית',            english: 'Hebrew',             flag: '🇮🇱' },
  { code: 'hi',    native: 'हिन्दी',           english: 'Hindi',              flag: '🇮🇳' },
  { code: 'mr',    native: 'मराठी',            english: 'Marathi',            flag: '🇮🇳' },
  { code: 'ne',    native: 'नेपाली',           english: 'Nepali',             flag: '🇳🇵' },
  { code: 'mai',   native: 'मैथिली',           english: 'Maithili',           flag: '🇮🇳' },
  { code: 'doi',   native: 'डोगरी',            english: 'Dogri',              flag: '🇮🇳' },
  { code: 'kok',   native: 'कोंकणी',           english: 'Konkani',            flag: '🇮🇳' },
  { code: 'sa',    native: 'संस्कृतम्',         english: 'Sanskrit',           flag: '🇮🇳' },
  { code: 'pa',    native: 'ਪੰਜਾਬੀ',            english: 'Punjabi',            flag: '🇮🇳' },
  { code: 'gu',    native: 'ગુજરાતી',           english: 'Gujarati',           flag: '🇮🇳' },
  { code: 'or',    native: 'ଓଡ଼ିଆ',             english: 'Odia',               flag: '🇮🇳' },
  { code: 'bn',    native: 'বাংলা',             english: 'Bengali',            flag: '🇧🇩' },
  { code: 'as',    native: 'অসমীয়া',           english: 'Assamese',           flag: '🇮🇳' },
  { code: 'mni',   native: 'ꯃꯤꯇꯩꯂꯣꯟ',          english: 'Meitei (Manipuri)',  flag: '🇮🇳' },
  { code: 'sat',   native: 'ᱥᱟᱱᱛᱟᱲᱤ',          english: 'Santali',            flag: '🇮🇳' },
  { code: 'ml',    native: 'മലയാളം',           english: 'Malayalam',          flag: '🇮🇳' },
  { code: 'ta',    native: 'தமிழ்',             english: 'Tamil',              flag: '🇮🇳' },
  { code: 'te',    native: 'తెలుగు',            english: 'Telugu',             flag: '🇮🇳' },
  { code: 'kn',    native: 'ಕನ್ನಡ',             english: 'Kannada',            flag: '🇮🇳' },
  { code: 'si',    native: 'සිංහල',             english: 'Sinhala',            flag: '🇱🇰' },
  { code: 'my',    native: 'မြန်မာဘာသာ',        english: 'Burmese',            flag: '🇲🇲' },
  { code: 'th',    native: 'ภาษาไทย',           english: 'Thai',               flag: '🇹🇭' },
  { code: 'lo',    native: 'ພາສາລາວ',           english: 'Lao',                flag: '🇱🇦' },
  { code: 'km',    native: 'ភាសាខ្មែរ',          english: 'Khmer',              flag: '🇰🇭' },
  { code: 'dz',    native: 'རྫོང་ཁ',             english: 'Dzongkha',           flag: '🇧🇹' },
  { code: 'ti',    native: 'ትግርኛ',              english: 'Tigrinya',           flag: '🇪🇷' },
  { code: 'am',    native: 'አማርኛ',              english: 'Amharic',            flag: '🇪🇹' },
  { code: 'om',    native: 'Afaan Oromoo',      english: 'Oromo',              flag: '🇪🇹' },
  { code: 'zh-cn', native: '中文（简体）',         english: 'Chinese Simplified', flag: '🇨🇳' },
  { code: 'zh-tw', native: '中文（繁體）',         english: 'Chinese Traditional',flag: '🇹🇼' },
  { code: 'yue',   native: '廣東話',              english: 'Cantonese',          flag: '🇭🇰' },
  { code: 'ja',    native: '日本語',              english: 'Japanese',           flag: '🇯🇵' },
  { code: 'ko',    native: '한국어',              english: 'Korean',             flag: '🇰🇷' },
  { code: 'mn',    native: 'Монгол',             english: 'Mongolian',          flag: '🇲🇳' },
  { code: 'ka',    native: 'ქართული',            english: 'Georgian',           flag: '🇬🇪' },
  { code: 'hy',    native: 'Հայերեն',            english: 'Armenian',           flag: '🇦🇲' },
  { code: 'ru',    native: 'Русский',            english: 'Russian',            flag: '🇷🇺' },
  { code: 'uk',    native: 'Українська',         english: 'Ukrainian',          flag: '🇺🇦' },
  { code: 'be',    native: 'Беларуская',         english: 'Belarusian',         flag: '🇧🇾' },
  { code: 'bg',    native: 'Български',          english: 'Bulgarian',          flag: '🇧🇬' },
  { code: 'mk',    native: 'Македонски',         english: 'Macedonian',         flag: '🇲🇰' },
  { code: 'sr',    native: 'Српски',             english: 'Serbian',            flag: '🇷🇸' },
  { code: 'kk',    native: 'Қазақша',            english: 'Kazakh',             flag: '🇰🇿' },
  { code: 'ky',    native: 'Кыргызча',           english: 'Kyrgyz',             flag: '🇰🇬' },
  { code: 'tg',    native: 'Тоҷикӣ',             english: 'Tajik',              flag: '🇹🇯' },
  { code: 'el',    native: 'Ελληνικά',           english: 'Greek',              flag: '🇬🇷' },
  { code: 'af',    native: 'Afrikaans',          english: 'Afrikaans',          flag: '🇿🇦' },
  { code: 'ak',    native: 'Akan',               english: 'Akan',               flag: '🇬🇭' },
  { code: 'ay',    native: 'Aymar aru',          english: 'Aymara',             flag: '🇧🇴' },
  { code: 'az',    native: 'Azərbaycanca',       english: 'Azerbaijani',        flag: '🇦🇿' },
  { code: 'bal',   native: 'بلوچی',              english: 'Balochi',            flag: '🇵🇰' },
  { code: 'bem',   native: 'Ichibemba',          english: 'Bemba',              flag: '🇿🇲' },
  { code: 'bm',    native: 'Bamanankan',         english: 'Bambara',            flag: '🇲🇱' },
  { code: 'br',    native: 'Brezhoneg',          english: 'Breton',             flag: '🏴' },
  { code: 'bs',    native: 'Bosanski',           english: 'Bosnian',            flag: '🇧🇦' },
  { code: 'ca',    native: 'Català',             english: 'Catalan',            flag: '🇪🇸' },
  { code: 'ceb',   native: 'Cebuano',            english: 'Cebuano',            flag: '🇵🇭' },
  { code: 'co',    native: 'Corsu',              english: 'Corsican',           flag: '🇫🇷' },
  { code: 'cs',    native: 'Čeština',            english: 'Czech',              flag: '🇨🇿' },
  { code: 'cy',    native: 'Cymraeg',            english: 'Welsh',              flag: '🏴' },
  { code: 'da',    native: 'Dansk',              english: 'Danish',             flag: '🇩🇰' },
  { code: 'de',    native: 'Deutsch',            english: 'German',             flag: '🇩🇪' },
  { code: 'ee',    native: 'Eʋegbe',             english: 'Ewe',                flag: '🇬🇭' },
  { code: 'en',    native: 'English',            english: 'English',            flag: '🇬🇧' },
  { code: 'es',    native: 'Español',            english: 'Spanish',            flag: '🇪🇸' },
  { code: 'et',    native: 'Eesti',              english: 'Estonian',           flag: '🇪🇪' },
  { code: 'eu',    native: 'Euskara',            english: 'Basque',             flag: '🇪🇸' },
  { code: 'ff',    native: 'Pulaar',             english: 'Fula',               flag: '🇸🇳' },
  { code: 'fi',    native: 'Suomi',              english: 'Finnish',            flag: '🇫🇮' },
  { code: 'fil',   native: 'Filipino',           english: 'Filipino',           flag: '🇵🇭' },
  { code: 'fj',    native: 'Vosa Vakaviti',      english: 'Fijian',             flag: '🇫🇯' },
  { code: 'fo',    native: 'Føroyskt',           english: 'Faroese',            flag: '🇫🇴' },
  { code: 'fr',    native: 'Français',           english: 'French',             flag: '🇫🇷' },
  { code: 'fy',    native: 'Frysk',              english: 'Frisian',            flag: '🇳🇱' },
  { code: 'ga',    native: 'Gaeilge',            english: 'Irish',              flag: '🇮🇪' },
  { code: 'gd',    native: 'Gàidhlig',           english: 'Scottish Gaelic',    flag: '🏴' },
  { code: 'gl',    native: 'Galego',             english: 'Galician',           flag: '🇪🇸' },
  { code: 'gn',    native: "Avañe'ẽ",            english: 'Guaraní',            flag: '🇵🇾' },
  { code: 'ha',    native: 'Hausa',              english: 'Hausa',              flag: '🇳🇬' },
  { code: 'haw',   native: 'ʻŌlelo Hawaiʻi',    english: 'Hawaiian',           flag: '🇺🇸' },
  { code: 'hil',   native: 'Hiligaynon',         english: 'Hiligaynon',         flag: '🇵🇭' },
  { code: 'hr',    native: 'Hrvatski',           english: 'Croatian',           flag: '🇭🇷' },
  { code: 'ht',    native: 'Kreyòl ayisyen',     english: 'Haitian Creole',     flag: '🇭🇹' },
  { code: 'hu',    native: 'Magyar',             english: 'Hungarian',          flag: '🇭🇺' },
  { code: 'id',    native: 'Bahasa Indonesia',   english: 'Indonesian',         flag: '🇮🇩' },
  { code: 'ig',    native: 'Igbo',               english: 'Igbo',               flag: '🇳🇬' },
  { code: 'ilo',   native: 'Ilokano',            english: 'Ilocano',            flag: '🇵🇭' },
  { code: 'is',    native: 'Íslenska',           english: 'Icelandic',          flag: '🇮🇸' },
  { code: 'it',    native: 'Italiano',           english: 'Italian',            flag: '🇮🇹' },
  { code: 'jv',    native: 'Basa Jawa',          english: 'Javanese',           flag: '🇮🇩' },
  { code: 'ku',    native: 'Kurdî',              english: 'Kurdish',            flag: '🇮🇶' },
  { code: 'lb',    native: 'Lëtzebuergesch',     english: 'Luxembourgish',      flag: '🇱🇺' },
  { code: 'lg',    native: 'Luganda',            english: 'Luganda',            flag: '🇺🇬' },
  { code: 'ln',    native: 'Lingála',            english: 'Lingala',            flag: '🇨🇩' },
  { code: 'lt',    native: 'Lietuvių',           english: 'Lithuanian',         flag: '🇱🇹' },
  { code: 'lv',    native: 'Latviešu',           english: 'Latvian',            flag: '🇱🇻' },
  { code: 'mg',    native: 'Malagasy',           english: 'Malagasy',           flag: '🇲🇬' },
  { code: 'mi',    native: 'Te Reo Māori',       english: 'Māori',              flag: '🇳🇿' },
  { code: 'mk',    native: 'Македонски',         english: 'Macedonian',         flag: '🇲🇰' },
  { code: 'ms',    native: 'Bahasa Melayu',      english: 'Malay',              flag: '🇲🇾' },
  { code: 'mt',    native: 'Malti',              english: 'Maltese',            flag: '🇲🇹' },
  { code: 'nah',   native: 'Nāhuatl',            english: 'Nahuatl',            flag: '🇲🇽' },
  { code: 'nl',    native: 'Nederlands',         english: 'Dutch',              flag: '🇳🇱' },
  { code: 'no',    native: 'Norsk',              english: 'Norwegian',          flag: '🇳🇴' },
  { code: 'nr',    native: 'isiNdebele',         english: 'Ndebele (South)',    flag: '🇿🇦' },
  { code: 'ny',    native: 'Chichewa',           english: 'Chichewa',           flag: '🇲🇼' },
  { code: 'oc',    native: 'Occitan',            english: 'Occitan',            flag: '🇫🇷' },
  { code: 'pl',    native: 'Polski',             english: 'Polish',             flag: '🇵🇱' },
  { code: 'pt',    native: 'Português',          english: 'Portuguese',         flag: '🇧🇷' },
  { code: 'ro',    native: 'Română',             english: 'Romanian',           flag: '🇷🇴' },
  { code: 'rw',    native: 'Kinyarwanda',        english: 'Kinyarwanda',        flag: '🇷🇼' },
  { code: 'sk',    native: 'Slovenčina',         english: 'Slovak',             flag: '🇸🇰' },
  { code: 'sl',    native: 'Slovenščina',        english: 'Slovenian',          flag: '🇸🇮' },
  { code: 'sm',    native: 'Gagana Samoa',       english: 'Samoan',             flag: '🇼🇸' },
  { code: 'sn',    native: 'ChiShona',           english: 'Shona',              flag: '🇿🇼' },
  { code: 'so',    native: 'Soomaali',           english: 'Somali',             flag: '🇸🇴' },
  { code: 'sq',    native: 'Shqip',              english: 'Albanian',           flag: '🇦🇱' },
  { code: 'st',    native: 'Sesotho',            english: 'Sotho',              flag: '🇱🇸' },
  { code: 'su',    native: 'Basa Sunda',         english: 'Sundanese',          flag: '🇮🇩' },
  { code: 'sv',    native: 'Svenska',            english: 'Swedish',            flag: '🇸🇪' },
  { code: 'sw',    native: 'Kiswahili',          english: 'Swahili',            flag: '🇰🇪' },
  { code: 'tk',    native: 'Türkmençe',          english: 'Turkmen',            flag: '🇹🇲' },
  { code: 'tn',    native: 'Setswana',           english: 'Tswana',             flag: '🇧🇼' },
  { code: 'to',    native: 'Lea faka-Tonga',     english: 'Tongan',             flag: '🇹🇴' },
  { code: 'tpi',   native: 'Tok Pisin',          english: 'Tok Pisin',          flag: '🇵🇬' },
  { code: 'tr',    native: 'Türkçe',             english: 'Turkish',            flag: '🇹🇷' },
  { code: 'ts',    native: '\u0058itsonga',     english: 'Tsonga',             flag: '🇿🇦' },
  { code: 'uz',    native: "O'zbek",             english: 'Uzbek',              flag: '🇺🇿' },
  { code: 've',    native: 'Tshivenḓa',          english: 'Venda',              flag: '🇿🇦' },
  { code: 'vi',    native: 'Tiếng Việt',         english: 'Vietnamese',         flag: '🇻🇳' },
  { code: 'wo',    native: 'Wolof',              english: 'Wolof',              flag: '🇸🇳' },
  { code: 'xh',    native: 'isiXhosa',           english: 'Xhosa',              flag: '🇿🇦' },
  { code: 'yo',    native: 'Yorùbá',             english: 'Yoruba',             flag: '🇳🇬' },
  { code: 'zgh',   native: 'ⵜⴰⵎⴰⵣⵉⵖⵜ',          english: 'Tamazight',          flag: '🇲🇦' },
  { code: 'zu',    native: 'isiZulu',            english: 'Zulu',               flag: '🇿🇦' },
  { code: 'other', native: 'Other',              english: 'Other',              flag: '🌐' },
]
